#!/bin/sh

CONF_FILE="/htdocs/conf/conf.php"
BACKUP="/.git/dolibarr_conf/"

prev_head="$1"
new_head="$2"
chg_branch="$3"

if [ -z "$GIT_DIR" ]; then                                                  # Test si vide. 
    exit 1
fi

if [ $chg_branch -ne 1 ]; then
    exit 1
fi


rldesc="$(git reflog | head -n 1)"

before="$(echo $rldesc | sed -e 's/^.* from \(.*\) to.*/\1/')"
after="$(echo $rldesc | sed -e 's/^.*to \(.*\)/\1/')"


for tag in $(git for-each-ref --format='%(refname)' refs/tags/ | sed 's/refs\/tags\///'); do
    hash="$(git show-ref -s $tag)"
	if [ "$hash" = "$before" ]; then
		before=$tag
	elif [ "$hash" = "$after" ]; then
		after=$tag
	fi
done


toplevel="$(git rev-parse --show-toplevel)"					# Get racine
prev_branch=$before											# Get branch/tag name before checkout
new_branch=$after											# Get branch/tag name after checkout


if [ $prev_branch = $new_branch ]; then
    exit 0
fi

if [ ! -d "$toplevel$BACKUP" ]; then
	mkdir -p $toplevel$BACKUP                                                   # Create dossier backup
fi

if [ -f $toplevel$CONF_FILE ]; then
    echo "Backing up "$CONF_FILE" into conf.php."$prev_branch
    mv $toplevel$CONF_FILE $toplevel$BACKUP"conf.php."$prev_branch          # Backing up conf.php
fi

if [ -f $toplevel$BACKUP"conf.php."$new_branch ]; then
    echo "Restoring "$BACKUP"conf.php."$new_branch
    mv $toplevel$BACKUP"conf.php."$new_branch $toplevel$CONF_FILE           # Restauring backup conf.php
else
    echo "No backup found for this branch."

    exec < /dev/tty                                                         # Input
    while true; do

        read -p "Do you want to keep the current configuration? (Y/n)" yn
        if [ -z "$yn" ]; then
            yn='Y'
        fi

        case $yn in
            [Yy]*)
                cp $toplevel$BACKUP"conf.php."$prev_branch $toplevel$CONF_FILE; break
                ;;
            [Nn]*)
                exit
                ;;
            *)
                echo "Please answer y or n."
                ;;
        esac

    done
fi

exit 0
