#!/bin/sh
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

CONF_FILE="/htdocs/conf/conf.php"
BACKUP="/.git/dolibarr_conf/"

prev_head="$1"
new_head="$2"
chg_branch="$3"

if [ -z "$GIT_DIR" ]; then                                                  # Test si vide. 
    exit 1
fi

if [ $chg_branch -ne 1 ]; then
    exit 1
fi

rldesc="$(git reflog | head -n 1)"

before="$(echo $rldesc | sed -e 's/^.* from \(.*\) to.*/\1/')"
after="$(echo $rldesc | sed -e 's/^.*to \(.*\)/\1/')"

if [ ! -z "$(git tag | grep -Fx $before)" ]; then
    before="$(git rev-list -n 1 $before)"
fi

if [ ! -z "$(git tag | grep -Fx $after)" ]; then
    after="$(git rev-list -n 1 $after)"
fi

toplevel="$(git rev-parse --show-toplevel)"					# Get racine
prev_branch=$before								# Get branch/tag name before checkout
new_branch=$after								# Get branch/tag name after checkout

if [ $prev_branch = $new_branch ]; then
    exit 0
fi

if [ ! -d "$toplevel$BACKUP" ]; then
	mkdir -p $toplevel$BACKUP                                                   # Create dossier backup
fi

if [ -f $toplevel$CONF_FILE ]; then
    if [ "$color_prompt" = yes ]; then
        echo "\033[1;35mBacking up\033[0m ${CONF_FILE} into conf.php.${prev_branch}"
    else
        echo "Backing up ${CONF_FILE} into conf.php.${prev_branch}"
    fi
    mv "${toplevel}${CONF_FILE}" "${toplevel}${BACKUP}conf.php.${prev_branch}"          # Backing up conf.php
fi

if [ -f $toplevel$BACKUP"conf.php."$new_branch ]; then
    if [ "$color_prompt" = yes ]; then 
        echo "\033[1;35mRestoring\033[0m ${BACKUP}conf.php.${new_branch}"
    else
        echo "Restoring ${BACKUP}conf.php.${new_branch}"
    fi
    mv "${toplevel}${BACKUP}conf.php.${new_branch}" "${toplevel}${CONF_FILE}"           # Restauring backup conf.php
else
    echo "No backup found for this branch."

    exec < /dev/tty                                                         # Input
    while true; do

        read -p "Do you want to keep the current configuration? (Y/n)" yn
        if [ -z "$yn" ]; then
            yn='Y'
        fi

        case $yn in
            [Yy]*)
                cp $toplevel$BACKUP"conf.php."$prev_branch $toplevel$CONF_FILE; break
                ;;
            [Nn]*)
                exit
                ;;
            *)
                echo "Please answer y or n."
                ;;
        esac

    done
fi

exit 0

